name: trackie_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.2'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
<<<<<<< HEAD
  camera: ^0.11.0+1
  permission_handler: ^11.3.1
=======
  app_settings: ^5.1.1
  shake: ^2.2.0
  
  # Adicionado para funcionalidade Bluetooth
  flutter_blue_plus: ^1.31.18
>>>>>>> 7f4e52c436ba1e69861ff044e4eabf9639f7ecd8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

dependency_overrides:
  sensors_plus: ^5.0.1

flutter:
  uses-material-design: true

