# ios/Podfile

# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network requests to Segment, Inc. to help improve CocoaPods.
# You can turn off analytics by uncommenting the following line.
# ENV['COCOCOAPODS_DISABLE_STATS'] = 'true'

# Load the Flutter-generated Pods
flutter_application_path = '../'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  install! 'cocoapods', :warn_for_unused_master_specs_repo => false
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
